#!/usr/bin/env python3
"""Generate the differential-test vector fixture for the Rust test suite.

Emits `tests/vectors_differential.txt`: a set of (message length, AAD length)
pairs whose ciphertext and tag are produced by the **independent** reference
implementation in `tools/ref_impl.py` — not by the Rust code under test.

The message and AAD bytes are deterministic functions of their lengths, so the
fixture only needs to store the lengths; `tests/differential_reference.rs`
reconstructs the inputs with the same formula and compares.

Usage:
    python3 tools/gen_test_vectors.py            # write the fixture
    python3 tools/gen_test_vectors.py --check    # verify it is current
"""
import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
OUT = os.path.join(ROOT, "tests", "vectors_differential.txt")

# Fixed key/nonce: the fixture stays small, and the point of these vectors is
# length coverage, not key diversity (the KATs and the property tests cover
# keys).
KEY = bytes((i * 17 + 3) % 256 for i in range(32))
NONCE = bytes((i * 29 + 5) % 256 for i in range(24))


#: (message length, AAD length) pairs.
#:
#: The lengths are chosen to straddle every internal boundary:
#:   * Poly1305 16-byte block           (15/16/17)
#:   * 4-block Poly1305 batch boundary  (63/64/65)
#:   * ChaCha20 64-byte block           (63/64/65, 127/128/129)
#:   * SSE2 / NEON 256-byte SIMD width  (255/256/257)
#:   * AVX2 512-byte SIMD width         (511/512/513)
#:   * 1024 and 2048 multiples, +-1
#: plus empty and single-byte messages, and AADs that are larger, smaller and
#: equal in size to the message (the Poly1305 length block concatenates both,
#: so their relative order matters).
PAIRS = [
    (0, 0), (0, 1), (0, 15), (0, 16), (0, 17), (0, 64), (0, 257),
    (1, 0), (1, 15), (1, 16), (1, 255), (1, 256),
    (2, 0),
    (15, 0), (16, 0), (17, 0),
    (31, 32), (32, 31), (33, 33),
    (63, 0), (64, 0), (65, 0),
    (63, 63), (64, 64), (65, 65),
    (79, 1), (80, 1), (81, 1),
    (127, 0), (128, 0), (129, 0),
    (191, 193), (192, 192), (193, 191),
    (255, 0), (256, 0), (257, 0),
    (255, 255), (256, 256), (257, 257),
    (511, 0), (512, 0), (513, 0),
    (1023, 0), (1024, 0), (1025, 0),
    (1025, 300), (2048, 0), (2049, 0),
]


def pt_for(n):
    return bytes((i * 37 + 11) % 256 for i in range(n))


def aad_for(n):
    return bytes((i * 91 + 7) % 256 for i in range(n))


def load_ref():
    spec = importlib.util.spec_from_file_location("ref", os.path.join(HERE, "ref_impl.py"))
    ref = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(ref)
    return ref


def build():
    ref = load_ref()
    lines = [
        "# Differential test vectors for XChaCha20-Poly1305-SIV.",
        "#",
        "# Generated by tools/gen_test_vectors.py from tools/ref_impl.py, which is",
        "# an independent implementation written from the RFC 8439 /",
        "# draft-irtf-cfrg-xchacha-03 pseudocode and the c2sp.org specification.",
        "# Do not edit by hand; re-run the generator.",
        "#",
        "# key   = " + KEY.hex(),
        "# nonce = " + NONCE.hex(),
        "#",
        "# plaintext[i] = (i * 37 + 11) % 256",
        "# aad[i]       = (i * 91 +  7) % 256",
        "#",
        "# <msg_len> <aad_len> <ciphertext_hex> <tag_hex>",
        "#",
        "# An empty ciphertext is written as `-` (an empty field would collapse",
        "# under whitespace splitting and shift the tag into the wrong column).",
        "# The tag is always 32 bytes, so it is never empty.",
        "",
    ]
    for n, a in PAIRS:
        ct, tag = ref.encrypt_x(KEY, NONCE, aad_for(a), pt_for(n))
        # The fixture must be self-consistent before it is written.
        assert ref.decrypt_x(KEY, NONCE, aad_for(a), ct, tag) == pt_for(n), (n, a)
        assert len(tag) == 32, (n, a)
        lines.append(f"{n} {a} {ct.hex() or '-'} {tag.hex()}")
    return "\n".join(lines) + "\n"


def main():
    text = build()
    if "--check" in sys.argv:
        with open(OUT) as fh:
            current = fh.read()
        if current == text:
            print(f"{OUT} is current ({len(PAIRS)} vectors)")
            return
        print(f"{OUT} is STALE -- re-run without --check")
        sys.exit(1)

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write(text)
    print(f"wrote {OUT} ({len(PAIRS)} vectors)")


if __name__ == "__main__":
    main()
